### ISSUE TITLE
some geometry does not render

### ISSUE THREAD

**Issue by djouallah** [datasciencecampus/community-visualizations#1]
I loaded a geojson geometry, some counties works fine other either show very small or not at all, I added the datastudio report and the source file

https://datastudio.google.com/reporting/984e4750-af1f-4f21-90d3-69ae7bd0c73c 

I think, the geometry is working, but for some reason, sometimes it become too small

**Comment by djouallah** [comment]
I notice if I filter by the area, all the map works

![image](https://user-images.githubusercontent.com/12554469/84617859-a672c400-af13-11ea-8d90-8425aebc82e0.png)

**Comment by mshodge** [comment]
Issue resolved [via Twitter](https://twitter.com/mim_djo/status/1271771565898625026).

Issue is due to the handling of GeoJSON objects. Have updated README for correct method of creating data.
