### ISSUE TITLE
Minor issue: hover breaking

### ISSUE THREAD

**Issue by MattExact** [datasciencecampus/community-visualizations#10]
Had a weird issue: when hovering over a region with null data, it would show the hover tooltip, but as soon as I hovered over a region with data it would break the map. Managed to fix this by using a custom metric and rounding which fixed the problem. Weirdly enough was fine when I did an identical query joining the shapes on a slightly different data set (albeit should have been the same format as both were imported to BQ from Sheets with NUMERIC type).
Makes me think it was some sort of data format/type issue, so if anyone has this issue, rounding solved it for me.

**Comment by mshodge** [comment]
Hi @MattExact sorry for delay, we've not had the chance to do this but we will have a look at it soon.

**Comment by mshodge** [comment]
Hi @MattExact I think I fixed this issue after you flagged but before I responded (I remember a similar bug). Feel free to reopen if it occurs again.
