### ISSUE TITLE
Show area name in tooltip

### ISSUE THREAD

**Issue by gtapko** [datasciencecampus/community-visualizations#11]
Is there any way that you could include a way to show the area name in the tooltip instead of the word "undefined"?

![image](https://user-images.githubusercontent.com/8189377/92045710-36741d00-ed4f-11ea-9dbe-7fd76ed4b057.png)

Thank you for your great work.

**Comment by MattExact** [comment]
I am also having this issue, was working fine a couple of days ago, whatever changes were made seem to have broken it
Another +1 for this project, it's very useful!

**Comment by mshodge** [comment]
Hi @gtapko sorry for delay, we've not had the chance to do this but we will have a look at it soon.

**Comment by mshodge** [comment]
Hi @gtapko  I think I fixed this issue after you flagged but before I responded (I remember a similar bug). Feel free to reopen if it occurs again. We have also added a tooltip field where you can CONCAT fields for a custom tooltip.
