### ISSUE TITLE
Legend not working properly with quantile and custom types

### ISSUE THREAD

**Issue by gtapko** [datasciencecampus/community-visualizations#12]
1) When using "Quantile" legend type and more than one metric, the legend does not update properly and retains the values for the first metric (please see gif below):

![quantile_error](https://user-images.githubusercontent.com/8189377/92433186-b09f0a00-f172-11ea-9677-cdc38d35d6a6.gif)

2) When using "User Breaks" type, if you define 6 categories there are repeated ranges in legend:

![image](https://user-images.githubusercontent.com/8189377/92433197-ba287200-f172-11ea-9a53-3cf06f09cdbb.png)

If you use 5 or 7 it works fine.

**Comment by mshodge** [comment]
Hi @gtapko we're removing the dropdown option from the choromap products now as Data Studios parameter field can be used with a filter to achieve a better result.
