### ISSUE TITLE
Apply filter

### ISSUE THREAD

**Issue by surfacescan** [datasciencecampus/community-visualizations#13]
Guys - this is amazing.  this is inspiring me and the team at www.viamo.io to create some of our own custom visualisations and publish them open source.  Bravo!

What would be involved in making it so that mouseclicks on the map could apply filters in the GDS report?  
That would be amazing!

**Comment by mshodge** [comment]
Hi @surfacescan that definitely would be nice. Must say I've yet to wrap my head around using community viz's as filters but hope to soon click my brain into gear and get something like this implemented.

**Comment by surfacescan** [comment]
Really cool. Yeah, I have no idea what would be involved. Let me know if
you want some help from any of our crew.

Bart

**Comment by sesi** [comment]
Hey all - this is an awesome d3 viz! Recently used it for a project and also noticed the "apply filter" feature could be implemented. 

Forked the repo and took a crack at it. I have a live demo of it [here](https://datastudio.google.com/reporting/2f0739c5-ea86-4270-b399-1b8ae76aaa6c/page/YBwqB) 

Manifest:
> gs://community-viz-sesi/

Not sure if there was a specific vision in mind for styling, but the opacity is lowered on filtered out dimensions so as to "highlight" the selected dimension/region. This is consistent with "apply filter" behavior of some other Data Studio visualizations. 

 Curious to get any initial thoughts!

**Comment by mshodge** [comment]
Hi @sesi that's fantastic work; it's been on my backlog for a while so I am so grateful for someone else having a go. It looks great to me; I'm happy with your style used - but may also explore removing all colours (making transparent) for all non-selected regions as some of our stakeholders misinterpret the legend colours when opacity is applied. Of the people I've talked to I guess the three options would be: 1) remove all colours for non-selected; 2) reduced opacity (like you've done) and 3) maintain colours but add a colour to the border of the selected area. Would be really keen to get your work implemented to the code though to start with and we can go from there. Would you mind submitting a Pull Request? We'll definitely acknowledge your work! Really great stuff!

**Comment by mshodge** [comment]
Also, sorry, it would also be great if we can worth together to get a [Multiple filter](https://developers.google.com/datastudio/visualization/interactions-guide#multiple_dimension_filter) working on this too as that'll be a next request from users I think.

**Comment by sesi** [comment]
Hi @mshodge thanks for the quick turnaround on the feedback and taking a look at my implementation. That sounds great! I'll go ahead and create a PR for these changes so that there's style and function that can be further iterated on. A lot of options for you all to consider with styling this feature in terms of how to best represent selected dimensions, unselected dimensions, and null dimensions.

Multiple filters makes sense as a next step for functionality and I'd also be interested in working with you all to get that in place!

**Comment by surfacescan** [comment]
Amazing work you guys!  Will definitely plan to use this filter feature
asap!

**Comment by mshodge** [comment]
They should be working on both choromap and choromap-lite now. All the thanks go to @sesi for their work on this. Will look at selecting multiple areas today if I have a chance, sesi did all the ground work for me anyway

**Comment by sesi** [comment]
Awesome - thanks! Glad we were able to get some mileage out of that code. Should be fun to see future iterations of this d3 tool

**Comment by surfacescan** [comment]
You guys are amazing. Am definitely staying tuned to these.
