### ISSUE TITLE
Choromap: dragging the map result in System Error

### ISSUE THREAD

**Issue by alepuccetti** [datasciencecampus/community-visualizations#16]
When dragging the map the visualisation returns an error.

<img width="919" alt="Screenshot 2020-11-04 at 16 33 46" src="https://user-images.githubusercontent.com/6577391/98131699-ce12fa80-1ebb-11eb-8933-9fda758e8080.png">

The JS console shows this error

<img width="798" alt="Screenshot 2020-11-04 at 16 36 34" src="https://user-images.githubusercontent.com/6577391/98132046-3e218080-1ebc-11eb-8708-44da765ea9a3.png">

**Comment by mshodge** [comment]
Hi @alepuccetti we're undergoing some changes to the code at the moment so bare with us. It should be stable at the moment. Is this for choromap or choromap-lite?

**Comment by alepuccetti** [comment]
Hi @mshodge,

I have tested the choromap.
