### ISSUE TITLE
Change map projection?

### ISSUE THREAD

**Issue by CharlesC1983** [datasciencecampus/community-visualizations#17]
Hey, thanks so much for this! I'm not sure if this is easy or something I'm missing elsewhere, but it would be very helpful for me to be able to use a different map projection. It seems like this vizualization only works EPSG:4326, so when I use a custom shapefile ([for example, this set of Congressional District and Electoral College maps](https://dkel.ec/map)), it distorts the shapes I'm trying to create. Is there a simple workaround I'm missing? I tried changing the projection on org2org, but I only get a blank result in the visualization.

**Comment by mshodge** [comment]
Hi @CharlesC1983 having the user choose the map projection has been on my list of things to do. I'll explore it more soon. Can I ask, are you using choromap-lite or choromap?

**Comment by CharlesC1983** [comment]
I'm using choromap. Thank you! I hate being that person who's never satisfied and chomping for the next enhancement, so I really appreciate you've made this available.

**Comment by mshodge** [comment]
Hi @CharlesC1983 I used choromap-lite and it seems the [Congressional District and Electoral College maps](https://dkel.ec/map) you signposted to already use EPSG:4326. I was able to get Electoral College Map version 1.0 and Electoral College Map version 2.0 to work as they were (by converting to GeoJSON from SHP). For Alternate Map: Distortion Cartogram I had to do a little more work as there were bad polygons in it and whilst it was EPSG:4326 projection, the coordinates were 10,000 times larger than normal. So I fixed the polygons and rescaled the coordinates to values between -90:90 and -180:180. I'll attach all GeoJSON files to this post as a zip file.

Screenshot of all plotting ok with choromap-lite:

<img width="1188" alt="Screenshot 2020-12-08 at 17 02 41" src="https://user-images.githubusercontent.com/15108577/101516664-a8c05300-3977-11eb-9095-a03236c32466.png">

[ElecColl_geojsons.zip](https://github.com/datasciencecampus/community-visualizations/files/5660645/ElecColl_geojsons.zip)

**Comment by mshodge** [comment]
I'll keep this issue open though as I would like to explore the user being able to use another projection apart from EPSG:4326. @CharlesC1983 if you have a dataset that uses another projection, let me know.

**Comment by mshodge** [comment]
I'll look at choromap too. But I nowadays use choromap-lite as it's simpler. Do you have a reason for using choromap?

Choromap lite example and guide: https://datastudio.google.com/s/h2DU_AGk3EM

**Comment by CharlesC1983** [comment]
Thanks for following up! To be honest, I didn't have a particular reason for using choromap and not choromap-lite. When I was googling around, choromap showed up higher in the search results so I started with that, and when I saw there was a lite version, I assumed it would be limited in some way. So I just kept using choromap. 

It's interesting that compared to the original, the plotting with choromap-lite still seems to stretch northern latitudes: 

<img width="571" alt="Screen Shot 2020-12-09 at 10 26 55 AM" src="https://user-images.githubusercontent.com/43584667/101650231-baead180-3a09-11eb-9b7e-ddd46092ff94.png">

I'll keep my eyes open for other projections apart from EPSG:4326 that could be useful to work with.

**Comment by mshodge** [comment]
Hi @CharlesC1983 it might be that the original isn't using Mercator projection then, which choromap/choromap-lite does by default. I have now added the ability in either to select from:

➡ Azimuthal Equal Area
➡ Azimuthal Equidistant
➡ Gnomonic
➡ Orthographic
➡ Stereographic
➡ Albers
➡ Conic Conformal
➡ ConicEqualArea
➡ ConicEquidistant
➡ Equirectangular
➡ Mercator
➡ Transverse Mercator

In the STYLE menu. 

Either that or the original's coordinates aren't the same as [the dataset](https://dkel.ec/map) we've used here (as the precise locations of areas are distorted on a global perspective because of the gaps between areas)

**Comment by mshodge** [comment]
See [here](https://datastudio.google.com/s/nPNalYz9Kl8) for projections example using choromap-lite and [here](https://datastudio.google.com/s/pXLeKkS8zTs) for choromap.

**Comment by mshodge** [comment]
Hi @CharlesC1983 Equirectangular seems to be a good match.
