### ISSUE TITLE
Adding x-axis labels and setting y-axis range for violin plots

### ISSUE THREAD

**Issue by ahanif19** [datasciencecampus/community-visualizations#18]
These community visualizations are awesome. Thanks for your work on these!

Had a couple of questions and I'm not sure if these are work in progress or if I just overlooked something.

- For the violin plot, it doesn't like look one can label the x-axis for each violin (for example, I'm trying to do one plot per day for my data). 

- Is it possible to adjust the y-axis? Seems like it auto-adjusts based on the range of the dimension. Reason I ask is I have data that is clustered around zero (but also includes entries closer to 1). Result is a violin that doesn't look great (and I realize that's a function of the data) but would be helpful to be able to modify the axis. I suppose another solution here is for me to just drop outlier values.

Thanks again

**Comment by mshodge** [comment]
Hi @ahanif19 thanks for the message. I'll look into adding both your requests soon, they are both possible. I'll drop you a message on here when it's done.

**Comment by mshodge** [comment]
Hi @ahanif19 

I've made the changes to the development visualisation, you can see an example [here](https://datastudio.google.com/s/kezoeNHrt2w). 

I've added an option to the STYLE tab for the following:

- min value for y axis (default is min value of all data)
- max value for y axis (default is max value of all data)
- x label name option

Hope this is ok. Let me know you thoughts. I will patch to the main visualisation today, but it takes up to 24 hours for it to refresh onto your use of the visualisation. I'll close this issue in 48 hours unless you have any other suggestions or recommendations.

Many thanks for getting in touch!

**Comment by ahanif19** [comment]
This looks great! Exactly what I was imagining. 

I'll keep an eye out for it today. Thank you!

**Comment by mshodge** [comment]
Brilliant, I'll close this issue. Feel free to open it if the changes aren't what you wanted, and also feel free to ask for any other implementations and I'll do my best to do them.
