### ISSUE TITLE
add an option to limit how many object can be shown

### ISSUE THREAD

**Issue by djouallah** [datasciencecampus/community-visualizations#2]
Currently, it show everything, which is good, but sometimes, it is nice to have an option to limit how many geometry can be show just for performance reason.

thanks

**Comment by mshodge** [comment]
Good suggestion. Will add soon.

**Comment by mshodge** [comment]
Am implementing this now. But keeping the default as 'max' which calls all polygons, as limiting the number of polygons by hand (without filtering data) should be a conscious decision I think (don't want to run into a scenario whereby the default reduces the polygons, which is misinterpreted as the number of polygons from the data filters in the report).

**Comment by djouallah** [comment]
yes absolutely !!!
