### ISSUE TITLE
Map does not work (July 29th '21)

### ISSUE THREAD

**Issue by craxyvirux** [datasciencecampus/community-visualizations#23]

**Comment by jesusbaron** [comment]
Yes, 
Since last night there must be a problem. In the datastudio where I used the visualization it does not work.

**Comment by adrian09-am** [comment]
The visualization is not working and there's not the input boundary geojson option anymore.

**Comment by lauramorillo** [comment]
I have created this PR https://github.com/datasciencecampus/community-visualizations/pull/24

I think that this can fix the issue with boundary geojson that was causing the maps not to be loaded.

**Comment by iileonardo88** [comment]
Has anyone managed to solve the problem? Mine still doesn't work.

**Comment by lauramorillo** [comment]
> Has anyone managed to solve the problem? Mine still doesn't work.

It's fixed on my fork but it has not been reviewed nor merged. Meanwhile you can publish a new version privately to use it if you need it fixed fast, you only need to upload the code to GCS with some changes to Manifest.

**Comment by iileonardo88** [comment]
thks!

**Comment by iileonardo88** [comment]
@lauramorillo i'm facing some issues trying to refer it from GCS. Could you help me telling me what do I need to change in the manifest.json. I changed the paths, but without success. Do I need to change the component id? Or do I need to put all the components or only the one I need?

**Comment by gtapko** [comment]
> It's fixed on my fork but it has not been reviewed nor merged. Meanwhile you can publish a new version privately to use it if you need it fixed fast, you only need to upload the code to GCS with some changes to Manifest.

Is there any solution for this? @lauramorillo could you elaborate more on GCS and Manifest meaning?

**Comment by surfacescan** [comment]
Hey @lauramorillo - please do share what you did to fix it.  I wonder if we should find a way to continue to support this plugin if @mshodge is not actively able to continue.

**Comment by mshodge** [comment]
Hi all. Apologies for not picking this up sooner - I have been on secondment away from the Data Science Campus since March 2021. I will pass this onto the team and ask someone to look into it. Failing that, I will try and have a look sometime in an evening. Apologies for the delay - only picking this up from the @ tag from @surfacescan

**Comment by surfacescan** [comment]
Thanks @mshodge - its still such a helpful plugin to compliment GDS. What are you up to now?

**Comment by surfacescan** [comment]
@mshodge - I believe that @lauramorillo has made a pull requests https://github.com/datasciencecampus/community-visualizations/pull/24#issue-700966287 that fixes the issue!

**Comment by adrian09-am** [comment]
Hi @mshodge, is there any new about fixing the issue? Thank you

**Comment by mshodge** [comment]
Hoping to get some spare time this afternoon to look at the PR and fix. Thanks for everyone's patience.
